name: JASSXPRO

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "MAFIA-USERBOT"

          replace: "BLAC-2.0-USERBOT"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: JASSXPRO

          commit_user_email: jassgamingyt2@gmail.com
